name: Docker

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

on:
  push:
    branches: [ master ]
    paths: 
     - '6/*'
     - '7/*'
     - '8/*'
     - '9/*'
     - '10/*'
     - '11/*'
     - '12/*'
     - 'all/*'
    # Publish semver tags as releases.
    tags: [ 'v*.*.*' ]
  pull_request:
    branches: [ master ]
#     paths: 
#      - '6/*'
#      - '7/*'
#      - '8/*'
#      - '9/*'
#      - '10/*'
#      - '11/*'
#      - '12/*'
#      - 'all/*'

env:
  REGISTRY: ghcr.io
  DOCKER_PKG_BASE_NAME: ghcr.io/shenxianpeng/clang-tools
  DOCKER_HUB_BASE_NAME: xianpengshen/clang-tools

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Extract branch name
        id: extract
        run: |
          if [ ${{ github.event_name }} == 'pull_request' ]; then
            echo "::set-output name=branch_name::$(echo ${GITHUB_HEAD_REF})"
          else
            echo "::set-output name=branch_name::$(echo ${GITHUB_REF#refs/heads/})"
          fi
            
      - name: Get changed files
        id: getfile
        run: |
          echo "::set-output name=files::$(git diff --name-only ${{ steps.extract.outputs.branch_name }} master)"
        
      - name: Log into Docker Hub
        # if: ${{ github.ref == 'refs/heads/master' }}
        uses: docker/login-action@28218f9b04b4f3f62068d7b6ce6ca5b26e35336c
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Log into registry ${{ env.REGISTRY }}
        # if: ${{ github.ref == 'refs/heads/master' }}
        uses: docker/login-action@28218f9b04b4f3f62068d7b6ce6ca5b26e35336c
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Extract metadata (tags, labels) for Docker
      # https://github.com/docker/metadata-action
      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          
      - name: Build Docker image matrix and push
        run: |
          for i in ${{ steps.getfile.outputs.files }}
          do
            if [[ "Dockerfile" =~ $i ]]; then
              echo "$i"
              TAG=`basename $i`
              
              docker buildx build -f $i
              docker tag ${DOCKER_HUB_BASE_NAME}:$TAG
              if [ ${{ github.ref }} == 'refs/heads/master' ]; then
                docker push ${DOCKER_HUB_BASE_NAME}:$TAG
              fi
              docker tag ${DOCKER_PKG_BASE_NAME}:$TAG
              if [ ${{ github.ref }} == 'refs/heads/master' ]; then
                docker push ${DOCKER_PKG_BASE_NAME}:$TAG
              fi
            fi
          done
